# Site settings
name: Mabida
title: The Massachusetts Branch of The International Dyslexia Association
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dyslexia-ma.org" # the base hostname & protocol for your site
cdn: "http://localhost:4000" # the option of loading css, js etc from a CDN. ie. cdn.dyslexia-ma.com

# important. if set to true, various parts of hte site start loading  CSS and JS from cloudfront, not the default S3.
use_cdn: false


twitter_username: DyslexiaMA
facebook_username: MA.Dyslexia

# Build settings
markdown: kramdown
permalinks: pretty
permalink: /blog/:title/

# configure pages (ensures all pages can be stashed out of the root / dir. )
include: ['_pages']
relative_permalinks: false

# pagination stuff
paginate:      8
paginate_path: '/blog/:num/'


# font path
css_dir: /assets/css
js_dir: /assets/js
font_dir: /assets/fonts
image_dir: /assets/images
thumbnail: mabida-icon.png

blogheaders_dir:
# Sass settings
sass:
    sass_dir: _includes/_sass
# when in prod, uncomment the next line
    style: :compressed




# DEFAULT VALUES
#
# The page header gets a default color, set here.
# It can be overriden in a page's yaml by creating values that look like:
#
# h1bg: ccc
#
# h1color: 000
default_page_header_bg: 2196f3
default_page_header_h1color: fff


# simpleform
# simpleform_API_token
simpleform_api_token: 549651cc0de4669b20e4356d02476343
#simpleform_redirect
simpleform_redirect: /contact-thanks
